"""rate_limits

Revision ID: 40021dfcfdd1
Revises: 
Create Date: 2026-04-03 21:45:06.947619+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40021dfcfdd1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usercheck',
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger(), server_default=sa.text("nextval('entity_id_seq')"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usercheck')
    # ### end Alembic commands ###
